spring:
  application:
    name: eureka-client-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:16000/eureka/

server:
  port: 16003

feign:
  hystrix:
    enabled: true # 开启hystrix
